apiVersion: apps/v1
kind: Deployment
metadata:
  name: default
spec:
  replicas: 6
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-container
          image: registry-intl.ap-southeast-3.aliyuncs.com/tinesh-poc-devops/java-webapp-docker:v6
          imagePullPolicy: Always
          ports:
            - containerPort: 80
  
